name: Build Heartbear agent image
on:
  # Trigger the action manually from the UI
  workflow_dispatch:
jobs:
  BuildHBserver:
    name: Build a new Hearbeat agent image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}     
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Prepare Client
        run: |
          curl -o ./HeartBeatSystem/HBclient/src/${{ vars.JAR_NAME }} -L ${{ vars.DWP_HBAGENT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./HeartBeatSystem/HBclient
          file: ./HeartBeatSystem/HBclient/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/ace:latest      
